apiVersion: 1.0.0
kind: Plugin
metadata:
  name: HTTP Gateway
  description: HTTP Gateway Plugin for the Reekoh IoT Platform
  documentation: README.md
  icon: asset/icon/reekoh200x200.png
  signupLink: https://myservice.com/signup # ??
  type: Storage
  price: 0
  tags:
    - gateway
    - http
  config:
    dataPath:
      label: Data Path
      type: String
      maxLength: 1000
      required: false
      default: /reekoh/data
      help: "(Optional) The path where device data is POSTed. Default: /reekoh/data."
      maxLength: 1000
    commandPath:
      label: Command Path
      type: String
      maxLength: 1000
      required: false
      help: "(Optional) The path where device messages or commands are POSTed. Default: /reekoh/command."
      maxLength: 1000
    username:
      label: Username
      type: String
      maxLength: 1000
      required: false
      help: "(Optional) HTTP Basic authentication username."
      maxLength: 1000
    password:
      label: Password
      type: Password
      maxLength: 1000
      required: false
      help: "(Optional) HTTP Basic authentication password."
      maxLength: 1000

  loadBalancing:
    method: http
    enableSticky: true

  release:
    version: 1.0.0
    notes: path/to/RELEASENOTESv1.0.0.md # ??
    image: path/to/docker/image # ??